import { getDaysInMonth, formatDate } from './dateUtils';

export const generateMonthlyReport = (year, month, attendanceData, dailyFullCost, messName) => {
    const daysInMonth = getDaysInMonth(month, year);
    const monthName = new Date(year, month, 1).toLocaleString('default', { month: 'long' });

    let fullDays = 0;
    let halfDays = 0;
    let absentDays = 0;

    for (let d = 1; d <= daysInMonth; d++) {
        const dateStr = formatDate(year, month, d);
        const status = attendanceData[dateStr]?.status;

        if (status === 'full') fullDays++;
        else if (status === 'half') halfDays++;
        else if (status === 'absent') absentDays++;
    }

    const totalMeals = fullDays + (halfDays * 0.5);
    const totalCost = (fullDays * dailyFullCost) + (halfDays * (dailyFullCost / 2));

    return `
*Mess Report - ${monthName} ${year}*
Mess: ${messName}

✅ Full Days: ${fullDays}
⚠️ Half Days: ${halfDays}
❌ Absent Days: ${absentDays}

🍽️ Total Meals: ${totalMeals}
💰 *Total Due: ₹${totalCost.toFixed(2)}*

Generated by Mess Tracker
`.trim();
};
